title: gorka.blog 
description: >- # this means to ignore newlines until "baseurl:"
  Un blog personal
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
lang: "es-ES"
permalink: /:title/

theme: garth-jekyll-theme
plugins:
  - jekyll-feed

exclude:
  - Dockerfile
  - docker-compose.yml
  - README.md
