version: "3.7"

services:
  blog:
    build: .
    command: bundle exec jekyll serve --host 0.0.0.0
    ports:
      - 4000:4000
    volumes:
      - .:/app
      - gem-cache:/bundle

volumes:
  gem-cache:
